---
id_rsa: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACAZCAZv743AqHC8Ttk76gM/4aH3fd6tQNMjEU+QthrKbgAAAKCMg3c5jIN3
  OQAAAAtzc2gtZWQyNTUxOQAAACAZCAZv743AqHC8Ttk76gM/4aH3fd6tQNMjEU+QthrKbg
  AAAECtFeX9X0fGReQpcOsqyIkrxIwiyYwT+2U2VDRmtVjmkxkIBm/vjcCocLxO2TvqAz/h
  ofd93q1A0yMRT5C2GspuAAAAF2RlcGxveUBwZXJmZWN0cGFuZWwuY29tAQIDBAUG
  -----END OPENSSH PRIVATE KEY-----
id_rsa_pub: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBkIBm/vjcCocLxO2TvqAz/hofd93q1A0yMRT5C2Gspu deploy@example.dev
